### ISSUE TITLE
Normandy Lake is missing from generated map

### ISSUE THREAD

**Issue by mcbeem** [XCSoar/mapgen#16]
Normandy Lake in Tennessee (35.46154684655526, -86.20685751541741) does not appear in the generated map file.

**Comment by lordfolken** [comment]
The vmap0 data is very flakey and very old. We need a reliabable process that extracts the topology from openstreetmap.

**Comment by lordfolken** [comment]
We now have new world wide Lake data. Please retest with https://mapgen.xcsoar.org/ and close the issue if ok.
