### ISSUE TITLE
mapgen not working at all

### ISSUE THREAD

**Issue by tkforbes** [XCSoar/mapgen#36]
I used the tool successfully on March 5, but I have been unable to generate anything for the past three days. No matter what combination of options I try, the response is always:

> Error: Generation failed!

**Comment by lordfolken** [comment]
Combination of errors. Disk space full, due to someone creating a 600 tile job. Something wrong with dns resolution..

**Comment by lordfolken** [comment]
So the box is back up and the maps are processing. there are 100 jobs in backlog, so it might take some time.

**Comment by tkforbes** [comment]
I received email notifications for the maps that I generated. However, the link is incomplete; it does not include a domain name. The following is the text of the message...

The XCSoar Map Generator has finished your map.
It can be downloaded at /download?uuid=6a96a0ce-a146-11ec-8922-525400c7f7bf
This link is valid for 7 days.

**Comment by lordfolken** [comment]
This is a known issue #33

**Comment by lordfolken** [comment]
The mentioned issue #33 is now fixed and should be rolled out automatically within the hour. Mapgen generally is available again. Thanks for reporting. :+1:
