### ISSUE TITLE
Server not generating any maps

### ISSUE THREAD

**Issue by biscuit112** [XCSoar/mapgen#60]
Hi,  I have been trying for a few hours now and i need to generate a map but it says its "working" then says "Error: Generation failed". I have tried on different browsers, drawing out the boundaries,and manually entering the Lat/long.  Nothing works.   I read somewhere the server could be reset?  I hope we haven't lost this map creation feature XCsoar is a staple to my flying.

**Comment by lordfolken** [comment]
I'll have a look

**Comment by lordfolken** [comment]
issue is due to expired ceritficate that wasn't replaced properly by the automation. 
Fixed the job
errornous mapgen jobs are being restarted.
